name: prerelease.yml
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+-rc']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Compile binary
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/moorenew
          generate_release_notes: true
          prerelease: true
          token: '${{ secrets.TOKEN }}'

